name: crypto_icons
description: A comprehensive Flutter package providing access to 474+ cryptocurrency icons as a custom font. Optimized for commercial applications with MIT license.
version: 1.0.0
repository: https://github.com/kemetic-labs/crypto-icons
homepage: https://github.com/kemetic-labs/crypto-icons
issue_tracker: https://github.com/kemetic-labs/crypto-icons/issues
documentation: https://github.com/kemetic-labs/crypto-icons#readme
publish_to: https://pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  golden_toolkit: ^0.15.0

flutter:
  fonts:
    - family: CryptocurrencyIcons
      fonts:
        - asset: assets/fonts/cryptocurrency-icons.ttf
