name: Flutter Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        flutter-version: ['3.29.0']
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: 'stable'
      
      - name: Install FVM
        run: |
          dart pub global activate fvm
          fvm install ${{ matrix.flutter-version }}
          fvm use ${{ matrix.flutter-version }}
      
      - name: Install dependencies
        run: fvm flutter pub get
      
      - name: Verify formatting
        run: fvm dart format --output=none --set-exit-if-changed .
      
      - name: Analyze project source
        run: fvm flutter analyze
      
      - name: Run tests
        run: fvm flutter test --coverage
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
